// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPets = `-- name: CountPets :one
SELECT
  COUNT(*)
FROM
  pets
`

func (q *Queries) CountPets(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPets)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPet = `-- name: CreatePet :one
INSERT INTO
  pets (name, photoURL) VALUES ($1, $2) RETURNING id
`

type CreatePetParams struct {
	Name     string
	Photourl string
}

func (q *Queries) CreatePet(ctx context.Context, arg CreatePetParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPet, arg.Name, arg.Photourl)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePet = `-- name: DeletePet :exec
DELETE FROM pets
WHERE
  id = $1
`

func (q *Queries) DeletePet(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePet, id)
	return err
}

const getPet = `-- name: GetPet :one
SELECT
  id,
  category_id,
  name,
  photoURL,
  sold
FROM
  pets
WHERE
  id = $1
`

type GetPetRow struct {
	ID         int64
	CategoryID pgtype.Int8
	Name       string
	Photourl   string
	Sold       bool
}

func (q *Queries) GetPet(ctx context.Context, id int64) (GetPetRow, error) {
	row := q.db.QueryRow(ctx, getPet, id)
	var i GetPetRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Photourl,
		&i.Sold,
	)
	return i, err
}

const listPets = `-- name: ListPets :many
SELECT
  id,
  category_id,
  name,
  photoURL,
  sold
FROM
  pets
LIMIT
  $2::integer
OFFSET
  $1::integer
`

type ListPetsParams struct {
	Offset int32
	Limit  int32
}

type ListPetsRow struct {
	ID         int64
	CategoryID pgtype.Int8
	Name       string
	Photourl   string
	Sold       bool
}

func (q *Queries) ListPets(ctx context.Context, arg ListPetsParams) ([]ListPetsRow, error) {
	rows, err := q.db.Query(ctx, listPets, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPetsRow
	for rows.Next() {
		var i ListPetsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Photourl,
			&i.Sold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePet = `-- name: UpdatePet :exec
UPDATE pets
SET
  name = $2
WHERE
  id = $1
`

type UpdatePetParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpdatePet(ctx context.Context, arg UpdatePetParams) error {
	_, err := q.db.Exec(ctx, updatePet, arg.ID, arg.Name)
	return err
}
